from distutils.core import setup
from setuptools import find_packages
from naja import __version__

with open("README.md", "r") as f:
    long_description = f.read()

setup(name=r'naja',
      version=__version__,
      license=r'Apache License Version 2.0',
      author=r'xiami',
      author_email=r'gaohlsilence@163.com',
      description=r'Async Suite For Python',
      long_description=long_description,
      long_description_content_type=r'text/markdown',
      url=r'https://github.com/xiaoxiamiya/naja.git',
      packages=find_packages(),
      python_requires=r'>= 3.8',
      platforms=[r"all"],
      install_requires=[
          r'APScheduler==3.7.0',
          r'Jinja2==2.11.3',
          r'Pillow==8.1.2',
          r'PyJWT==2.0.1',
          r'SQLAlchemy==1.3.23',
          r'WTForms==2.3.3',
          r'aiohttp==3.7.4',
          r'aiomysql==0.0.21',
          r'aioredis==1.3.1',
          r'async-timeout==3.0.1',
          r'cachetools==4.2.1',
          r'cryptography==3.4.6',
          r'fastapi==0.63.0',
          r'gunicorn==20.0.4',
          r'hiredis==1.1.0',
          r'httptools==0.1.1',
          r'loguru==0.5.3',
          r'motor==2.3.1',
          r'mq-http-sdk==1.0.3',
          r'ntplib==0.3.4',
          r'numpy==1.20.1',
          r'protobuf==3.15.5',
          r'psutil==5.8.0',
          r'pyahocorasick==1.4.1',
          r'pytest-asyncio==0.14.0',
          r'pytest==6.2.2',
          r'python-multipart==0.0.5',
          r'python-stdnum==1.16',
          r'pyzmq==22.0.3',
          r'qrcode==6.1',
          r'terminal-table==2.0.1',
          r'tornado-jinja2==0.2.4',
          r'tornado==6.1.0',
          r'ujson==4.0.2',
          r'uvicorn==0.13.4',
          r'uvloop==0.15.2;sys_platform!="win32"',
          r'wtforms-tornado==0.0.2',
          r'xlwt==1.3.0',
          r'xmltodict==0.12.0'
      ],
      classifiers=[
          r'Programming Language :: Python :: 3.8',
          r'License :: OSI Approved :: Apache Software License',
          r'Operating System :: POSIX :: Linux',
      ],
      )
